# Setup
title:               JADSB 
tagline:             'Just another data science blog'
description:         'A blog on all things data science related'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Bernard Chan 
  url:               https://www.linkedin.com/in/bslchan/
  twitter:           @bslc

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
### google_analytics_id: #UA-XXXX-Y
