# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            JADSB
tagline:          'Just Another Data Science Blog'
description:      'A blog on all things data science related'
# 'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://bslc.github.io
baseurl:          /

author:
  name:           'Bernard Chan'
  url:            https://www.linkedin.com/in/bslchan/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/bslc/
